// sdk/wasm/src/raw.ts
//
// Low-level FFI bridge to the Emscripten-generated SCC module.
//
// `scc.js` is generated by `emscripten/build.sh` and lives next to the
// compiled `.wasm`. We declare the Module shape we expect and load the
// module exactly once per JS context.
//
// REQ-027 — every async API uses real Promises. The Emscripten loader is
// already Promise-returning; we wrap it without polyfills.

// ---------------------------------------------------------------------------
// Module shape
//
// Emscripten with -sMODULARIZE=1 -sEXPORT_NAME=createSCC produces a default
// export that is `(moduleArg?) => Promise<Module>`. The Module instance has
// the runtime exports (HEAPU8 etc.) and the C functions prefixed with `_`.
//
// We model only the surface we use; expanding the type is safe later.
// ---------------------------------------------------------------------------

export interface SCCModule {
    /** Heap views; re-fetched on every access because ALLOW_MEMORY_GROWTH=1
     *  may replace the underlying ArrayBuffer on a _malloc that grows the
     *  heap. Always read these freshly after any allocation. */
    readonly HEAPU8: Uint8Array;
    readonly HEAPU16: Uint16Array;
    readonly HEAP32: Int32Array;

    /** libc-style allocators in the WASM heap. */
    _malloc(size: number): number;
    _free(ptr: number): void;

    /** SCC C ABI (see cabi/include/libscc.h). All pointers and sizes are
     *  numbers in WASM32. */
    _scc_init(): number;
    _scc_destroy(ctx: number): void;
    _scc_encode_frame(
        ctx: number,
        depth: number,
        depth_stride: number,
        width: number,
        height: number,
        bit_depth: number,
        out_sei: number,
        out_cap: number,
        out_len_ptr: number
    ): number;
    _scc_decode_sei(
        ctx: number,
        sei: number,
        sei_len: number,
        out_depth: number,
        out_stride: number,
        out_width_ptr: number,
        out_height_ptr: number,
        out_bit_depth_ptr: number
    ): number;
    _scc_set_param(ctx: number, key: number, value: number): number;
    _scc_get_last_error(ctx: number): number; // returns char* into HEAPU8

    /** Emscripten runtime helpers exposed via EXPORTED_RUNTIME_METHODS. */
    ccall(name: string, returnType: string | null, argTypes: string[], args: unknown[]): unknown;
    cwrap(name: string, returnType: string | null, argTypes: string[]): (...args: unknown[]) => unknown;
}

/** Emscripten config -- only the fields we set. */
export interface SCCModuleConfig {
    /** Resolves asset filenames (notably "scc.wasm") to absolute URLs.
     *  Defaults to `new URL(file, import.meta.url)` so the .wasm is
     *  fetched relative to where the JS entry point lives. */
    locateFile?(path: string, prefix: string): string;
    /** Optional console redirector. */
    print?(text: string): void;
    printErr?(text: string): void;
}

export type SCCFactory = (config?: SCCModuleConfig) => Promise<SCCModule>;

// ---------------------------------------------------------------------------
// One-shot loader.
//
// The Emscripten module is loaded lazily on first call. Subsequent calls
// return the cached promise -- multiple SCCEncoder/SCCDecoder instances
// share the same WASM instance, which keeps allocations and the JIT'd
// codec tables hot.
// ---------------------------------------------------------------------------

let modulePromise: Promise<SCCModule> | null = null;

export function getModule(): Promise<SCCModule> {
    if (!modulePromise) {
        modulePromise = (async () => {
            const factory = await loadFactory();
            const mod = await factory({
                locateFile: (path: string) => {
                    if (path.endsWith('.wasm')) {
                        return new URL('./scc.wasm', import.meta.url).href;
                    }
                    return path;
                },
            });
            return mod;
        })();
    }
    return modulePromise;
}

/** Reset the cached module (for tests; do NOT call in production -- it
 *  leaves any live ctx pointers dangling). */
export function _resetModuleForTests(): void {
    modulePromise = null;
}

async function loadFactory(): Promise<SCCFactory> {
    // The Emscripten output is a UMD-ish module that detects ESM vs CJS.
    // Under NodeNext + ESM we import the .js as the default export.
    // The relative path is resolved by the package consumer's bundler or by
    // the Node ESM loader.
    const url = new URL('./scc.js', import.meta.url).href;
    // In Node we can `import()` a file:// URL directly. In browsers the
    // bundler is expected to handle this; the URL is resolved at build time.
    const mod = (await import(/* @vite-ignore */ url)) as { default: SCCFactory };
    return mod.default;
}

// ---------------------------------------------------------------------------
// Helpers shared by the encoder / decoder facade.
// ---------------------------------------------------------------------------

/** Read a NUL-terminated C string out of the WASM heap. Returns "" for
 *  null pointers. Walks at most `max` bytes before giving up (defensive
 *  guard against unterminated strings). */
export function readCString(mod: SCCModule, ptr: number, max = 4096): string {
    if (ptr === 0) return '';
    const heap = mod.HEAPU8;
    let end = ptr;
    const limit = Math.min(ptr + max, heap.length);
    // Strict-mode-clean: indexed read returns `number | undefined`; treat
    // an out-of-range read (which shouldn't happen given the `end < limit`
    // guard) as a string terminator just to be safe.
    while (end < limit) {
        const b = heap[end];
        if (b === 0 || b === undefined) break;
        ++end;
    }
    return new TextDecoder().decode(heap.subarray(ptr, end));
}

/** Read scc_get_last_error and return as JS string. */
export function readLastError(mod: SCCModule, ctx: number): string {
    const ptr = mod._scc_get_last_error(ctx);
    return readCString(mod, ptr);
}

/** Scoped WASM allocator. Every malloc'd pointer is queued for free()
 *  on release(); call from a `finally` block to guarantee no leaks even
 *  on the error path. [Ultrathink #1] */
export class WASMScope {
    private allocs: number[] = [];
    constructor(private mod: SCCModule) {}

    malloc(size: number): number {
        const p = this.mod._malloc(size);
        if (p === 0) {
            // OOM in WASM heap. Free anything we already allocated.
            this.release();
            throw new Error('WASM _malloc failed (out of memory)');
        }
        this.allocs.push(p);
        return p;
    }

    /** Allocate and copy a JS Uint8Array into the WASM heap. */
    mallocCopy(bytes: Uint8Array): number {
        const p = this.malloc(bytes.byteLength);
        // Re-read HEAPU8 after malloc -- the heap may have grown.
        this.mod.HEAPU8.set(bytes, p);
        return p;
    }

    /** Allocate and zero-fill an int32 slot (size_t / int output param). */
    mallocInt32(): number {
        const p = this.malloc(4);
        this.mod.HEAP32[p >> 2] = 0;
        return p;
    }

    release(): void {
        for (const p of this.allocs) this.mod._free(p);
        this.allocs.length = 0;
    }
}
